### ISSUE TITLE
be7e0ae breaks translations

### ISSUE THREAD

**Issue by belegdol** [RaphaelKimmig/Gnome-Presentation-Mode#12]
This was originally reported into Fedora Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=754928
Basically, whenever this extension is installed, gnome-shell translations would stop working. The extension does not even need to be activated. Screenshots:
https://bugzilla.redhat.com/attachment.cgi?id=534363
https://bugzilla.redhat.com/attachment.cgi?id=534364

**Comment by Mystro256** [comment]
Are you able to do a bisect?

**Comment by belegdol** [comment]
The previous snapshot available in Fedora, c3ce6b2, was not working with gnome 3.2 at all. Given that there is exactly one commit in between, I do not think it bisecting makes a whole lot of sense.
Having said that, I once had a similar problem with the nautilus extension for gnome-mplayer, revisions from 1243 to 1245 seem to contain the fix:
http://code.google.com/p/gnome-mplayer/source/detail?r=1243

**Comment by Mystro256** [comment]
hmmm true say, I don't have time to look into it myself, but thanks for the info

**Comment by Mystro256** [comment]
You can try doing a bisect, but change function main(extensionMeta) to function init(extensionMeta) in extension.js and "shell-version" to [3.2] in metadata.json. This should make the older commits compatible with gnome-shell 3.2 but will require a restart of gnome shell every test though

**Comment by belegdol** [comment]
It is not so simple unfortunately, I did these changes but the extension does not load, gnome-tweak ui says there was an error loading it.

**Comment by Mystro256** [comment]
hmmm, I thought that would do the trick, does it still load? It may still load regardless, as it lacks the enable/disable methods. Also does looking glass give you any output? Furthermore, does it give you any output with the latest version? (i.e. with the translation issue)

**Comment by belegdol** [comment]
There are no errors in looking glass when the new version is loaded. When I try to load c3ce6b2 with the changes you mentioned, I get the error about Main.Panel.STANDARD_TRAY_ICON_SHELL_IMPLEMENTATION being undefined. Sorry for imprecise description, but I cannot seem to figure out how does one copy text from the looking glass' error pane.

**Comment by Mystro256** [comment]
Hmmm, is this particular to GNOME 3.2? or to a distro perhaps? What language do you have it set to? (so I can do some testing)

**Comment by belegdol** [comment]
Polish (pl_PL.utf8), and the distro is Fedora 16 x86_64.

**Comment by belegdol** [comment]
Keep in mind that not all the translation get screwed up - the one that does is for instance the popup showing up upon inserting the usb stick. Anything standard in gnome-shell should be in Polish actually, so anything which won't be is suspicious.

**Comment by Mystro256** [comment]
Sorry for the delay, but I've been busy. Due to inactivity and the fact that my pull request still hasn't been pulled yet, I figured it would be best to fork this project.
You can find it here: https://github.com/Mystro256/gnome-shell-extension-inhibit-applet
I did some fixing with translations and hopefully fixed this issue, please open an issue on my project if it still happens. :)
I also plan to post this on extensions.gnome.org shortly for easy installing.

Also if you let me know how to translate "Inhibit Suspend" (inhibit as in stop and suspend as in the suspend to ram or sleep mode of a computer) I can include a polish translation as well.

**Comment by Mystro256** [comment]
It looks like I fixed this after all (in my fork).

**Comment by belegdol** [comment]
Cool, I'll try to test it later.
Polish translation would be "Wstrzymaj usypianie"

**Comment by Mystro256** [comment]
Thanks, I added the translation :)
Just need to wait for extensions.gnome.org to review my extension
