### ISSUE TITLE
Change position

### ISSUE THREAD

**Issue by gimmy** [RaphaelKimmig/Gnome-Presentation-Mode#16]
It's possible to put the on/off menu under the Notify and over the Online Accounts? I think it would be a better choice.

**Comment by Mystro256** [comment]
I plan to merge my fork into this, an alternative solution has already been done in my fork.

I'll close this for now, just use my fork until I get around to merging/pulling it:
https://github.com/Mystro256/gnome-shell-extension-inhibit-applet
https://extensions.gnome.org/extension/233/inhibit-applet/

Please feel free to discuss another options here if you wish. I may move or add an option to move it into the user menu, but I'm a tad busy. Feel free to make a pull request if you're willing to do it and have an issue with the current design.

Thanks :)
