### ISSUE TITLE
Log-out/shutdown delayed when enabled

### ISSUE THREAD

**Issue by hashstat** [RaphaelKimmig/Gnome-Presentation-Mode#18]
When presentation mode is enabled, there is a 30 second delay between the log-out/shutdown request and the actual log-out/shutdown.  When presentation mode is off, there is no delay.

BTW, awesome extension.  Makes a great replacement for Caffeine, which doesn't work so well with Gnome 3.

**Comment by Mystro256** [comment]
just a note, this git seems to be fairly dead, you can use my fork instead if you would like:
https://github.com/Mystro256/gnome-shell-extension-inhibit-applet

**Comment by Mystro256** [comment]
my fork has been merged, and I'll take a look into this. Can you try the latest code and tell me how to replicate this with that? I'm having trouble replicating this issue.

**Comment by hashstat** [comment]
I pulled the latest changes down and checked things out.  The problem still exists.  When the "Inhibit Suspend" switch is in the off position, log out and power off work properly.  When the "Inhibit Suspend" switch is in the on position, running applications are closed and the desktop fades a bit at log out or power off but delays about 30 seconds before continuing.  Makes for a long shutdown if I forget to turn Inhibit off.

**Comment by Mystro256** [comment]
Alright thanks, I'll take a look into it.

**Comment by Mystro256** [comment]
This should be fixed thanks to the new pull; there should no longer be a reason for this to still happen due to the changes I made a few minutes ago.

Can confirm it as fixed with the latest git commit?

**Comment by hashstat** [comment]
I can confirm that there is no longer a delay for both logout and shutdown/restart.  I also noticed that now the inhibit state is remembered after logout/reboot, so if inhibit is enabled when I shutdown, the next time I start up it is still enabled and the screen saver will not activate until I disable inhibit.  Is that by design?  Is it possible to add an option to forget the state after logout and reboot?

Thanks again for your work on this.  It is a wonderful extension.

**Comment by Mystro256** [comment]
At the moment it's an unintentional design due to the nature of the fix. If you want, I'vew thought of a work around to semi-fix this.

The work around would be the following:
change line 49 to set it to true instead:

```
var powerManagementFlag = true;
```

and add the following line at about 55 to 60, after the line with "Inhibit Suspend" and before the line 'toggled':

```
InhibitMenu._powerSettings.set_boolean(POWER_KEY, true);
```

This just resets the the state on startup. If I can figure out a way to do it on shutdown, it would be much better.
