### ISSUE TITLE
Make the icon on the menu "clickable"

### ISSUE THREAD

**Issue by Mystro256** [RaphaelKimmig/Gnome-Presentation-Mode#24]
In order to allow for easy switching, I was suggested to try to make the icon clickable (either single or double, as I'm undecided) to allow fast toggle of the switch without opening the menu.

I personally like the menu aesthetically, so I was thinking either two options below for the best of both worlds:
- Single click with one mouse button to toggle, other to open menu
- Double click to toggle, single for menu

I need to figure out how to do either, so it's a work in progress.

**Comment by Mystro256** [comment]
Currently being worked on and has been pulled to the experimental branch. Feel free to test, I need feedback!

Here's a screenshot of the applet so far:
https://github.com/RaphaelKimmig/Gnome-Presentation-Mode/blob/experimental/Screenshot.png

**Comment by eonpatapon** [comment]
I think that having a menu with only one option is quite unproductive. Using just a single click to toggle on/off seems to me the way to go like the original Caffeine do.

Maybe when there will be more options they can be added to the menu that could be open with a right click

**Comment by Mystro256** [comment]
I agree; currently in the experimental branch I have just a button. I just need to test it on gnome 3.4 and etc before I can pull it.

**Comment by Mystro256** [comment]
I'm concluding this as fixed with the latest version (current git head). The current function is a simple button with text describing the state on mouse hover (locale available in English, French, Spanish, Italian and Polish at the moment)

I've uploaded this version on extensions.gnome.org for easy downloading:
https://extensions.gnome.org/extension/233/inhibit-applet/
