### ISSUE TITLE
user menu entry

### ISSUE THREAD

**Issue by christophlsa** [RaphaelKimmig/Gnome-Presentation-Mode#4]
Hey,

Wouldn’t it be better if the menu entry for presentation mode would stand under the "panelStatus" button in the top right corner?

The current problem is: If the laptop battery isn't plugged in, the power menu button is hidden and I can't activate the presentation mode.

Greetings

**Comment by Mystro256** [comment]
Agreed, I tried to use this for my desktop but no dice.

**Comment by Mystro256** [comment]
As a quick work around, I just replaced 'battery' in extension.js with 'a11y' to stick it in the accessibility menu.

**Comment by RaphaelKimmig** [comment]
Unfortunately I don't have a gnome shell installation here atm. As a quick workaround you can just do as Mystro256 suggested.

Replace the string 'battery' in extension.js:19 by 'a11y' or 'volume' to move the button to a different menu.

**Comment by Mystro256** [comment]
I have no interest in fixing this and I would rather just play with my fork instead: https://github.com/Mystro256/gnome-shell-extension-inhibit-applet

**Comment by Mystro256** [comment]
see the second comment in the following link for more info: https://github.com/RaphaelKimmig/Gnome-Presentation-Mode/issues/16
