### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fabaff** [RaphaelKimmig/Gnome-Presentation-Mode#5]
There is no license stated. Can you please add a COPYING file and a license statement to the header of the source files. Thanks in advance.

**Comment by RaphaelKimmig** [comment]
I've added a COPYING file. I think a license statement in each file is kinda overdoing it, it would be nearly as long as the source itself ;-)

**Comment by Mystro256** [comment]
Unfortunately I think it's necessary if you want to add this to the official repository :P, though you're very right Raphael haha

**Comment by fabaff** [comment]
Well, the Fedora Packaging Guidelines make a statement about the COPYING file. But as long as a license statement is available in the source header.

BTW,  the gnome-shell-extension-presentation-mode package is in Fedora Rawhide now and in testing for Fedora 15.

See https://admin.fedoraproject.org/pkgdb/acls/name/gnome-shell-extension-presentation-mode

**Comment by Mystro256** [comment]
This seems fixed, closing
